### ISSUE TITLE
Bug: unable to select certain images within additer

### ISSUE THREAD

**Issue by ngxingyu** [AY2223S1-CS2103T-W11-3/tp#113]
- [ ] (in unix) if the file is in a folder ending with " f", there is no way to select the image since the command will be split before the space, so the following command will not work: `additer d/2022-10-10 n/xxx p//test f/image.png f/feedback`. 
- [x] Within windows, typing certain illegal characters like `"` will throw a `java.nio.file.InvalidPathException` exception that isn't handled (Fixed in a2d8f67342242669ef930ddef9940eabe575dc80)

**Comment by zlimez** [comment]
If we use greedy regex before feeding to tokeniser then only the last occurrence of f/ will be considered as feedback? Like do our own parsing first. Problem is that feedback cannot contain f/ as well but I think that should be acceptable to the user.

**Comment by chloeelim** [comment]
Updated UG to specify file path constraint.
