### ISSUE TITLE
[PE-D][Tester E] description prefix for editcom is not intuitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-3/tp#164]
another small potential issue is that the prefix for editing the description is that p/ may not be an intuitive prefix for description. 

Proposed improvements:
 understand that d/ is used for deadline, so maybe can use a prefix like ds/  

![Screenshot 2022-10-28 at 4.34.22 PM.png](https://raw.githubusercontent.com/jgyj123/ped/main/files/95528428-5422-44b1-b6c9-d0bc061ebf61.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jgyj123/ped#4

**Comment by seelengxd** [comment]
I don't think we can change the command syntax anymore - feature freeze?

**Comment by zlimez** [comment]
Not an issue
