### ISSUE TITLE
Bug: large int indexes

### ISSUE THREAD

**Issue by chloeelim** [AY2223S1-CS2103T-W11-3/tp#214]
Try `delcus 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999`. Note that other commands that take indexes probably have this bug too. App is not crashing or throwing error, but the message displayed (invalid command format rather than invalid index) is misleading. 

Also, negative numbers maybe can also do better error handling (right now throws the invalid command format too), maybe a better error message would be to say that the index is invalid as it needs to be positive (but this is less of an issue).

One more thing I noticed (this is very minor) is that some messages in the result display would end in full stops, some miss out punctuation. it'd be good to standardise this if we have the time to do so.

**Comment by seelengxd** [comment]
Both handling of negative numbers and numbers above Integer.MAX_VALUE (2147483647) are getting handled in 
ParserUtil#parseIndex()
```java
   public static Index parseIndex(String oneBasedIndex) throws ParseException {
        String trimmedIndex = oneBasedIndex.trim();
        // this one returns true only for 1..Integer.MAX_VALUE
        if (!StringUtil.isNonZeroUnsignedInteger(trimmedIndex)) {
            throw new ParseException(MESSAGE_INVALID_INDEX);
        }
        return Index.fromOneBased(Integer.parseInt(trimmedIndex));
    }
```
