### ISSUE TITLE
Minor nit: clearer success message for open commands?

### ISSUE THREAD

**Issue by chloeelim** [AY2223S1-CS2103T-W11-3/tp#217]
Not sure if this is intended, but unlike other commands that would typically display the 'result' of the executed command (like how `opencus 1` shows 'Opened Customer____'), performing open commands without indexes would show their usage message instead which is a little weird and confusing.

Maybe we should display 'opened commission/ customer window' so things are clearer and more standardised?

<img width="1100" alt="Screenshot 2022-11-06 at 5 53 50 PM" src="https://user-images.githubusercontent.com/79991214/200164366-ad34c261-c702-4b6c-97e0-1f4d3ddbefc9.png">

<img width="1122" alt="Screenshot 2022-11-06 at 5 54 28 PM" src="https://user-images.githubusercontent.com/79991214/200164396-ea3f90d4-0c71-4cc8-9901-4fafa102d41b.png">

**Comment by seelengxd** [comment]
Hmm... true. This change is actually very recent - https://github.com/AY2223S1-CS2103T-W11-3/tp/pull/160

**Comment by chloeelim** [comment]
Closing this issue because this is a **feature NOT a bug**.

Rationale (from #160):
Display more useful CommandResult for opencom and opencus:
* Previously, opencus and opencom without the provided INDEX will not mention how the command actually works with a provided INDEX.
* Displaying the message usage when typing opencom or opencus will make it much easier for the user.

We should make it explicit to the user via the command result/ feedback that there are TWO such uses of open commands.
