### ISSUE TITLE
Commission's customer reference is not updated. :[

### ISSUE THREAD

**Issue by seelengxd** [AY2223S1-CS2103T-W11-3/tp#74]
- Commissions references of customer is currently not updated.

# Steps to replicate
1. `edit 2 n/test3`
1. go to commission pane
1. observe everything is gone 🤡 🤡 🤡 🤡 🤡 🤡 

# cause and possible solution
1. currently commissions do not get the updated customer reference. so, when the new stuff change, the isSameCustomer check will fail for the list filtering.
2. the customer being bidirectional was for filteredCommissionList but i think i can fix this by removing Customer from commissions and querying the selected Customer's commission set instead

Changes possibly required in `Customer.java` if the method is there, and `AddressBook.java`

**Comment by ngxingyu** [comment]
Another possible fix is to assign each new customer a uid that doesn't change when the customer is edited.

**Comment by ngxingyu** [comment]
Fixed by #82
