### ISSUE TITLE
Bug: Duplicate Commissions error when initialising AB

### ISSUE THREAD

**Issue by chloeelim** [AY2223S1-CS2103T-W11-3/tp#94]
<h1>WAIT ALSO I FORGOT TO SAY THERES ALSO  A BUG IN MY CODE THE FIX IS IN MY PR</h1>

<h1> WAIT i might be dumb hold on </h1>

While its possible to add commissions with the same name in AB now due to the refactoring #82, I think there's a major bug when initializing ArtBuddy Customers with Commissions of duplicate titles.

Steps to replicate:
1. To any Customer, add some Commission eg: `addcom n/Tokyo Ghoul Kaneki f/500 d/2022-10-10 s/False p/Unfamiliar, I will need to do up a reference board first. t/digital t/neon`
2. Then, repeat the same Commission in the same Customer to create another commission with the same title `d/2022-10-10 s/False p/Unfamiliar, I will need to do up a reference board first. t/digital t/neon`
3. Up till this step, AB should still be running fine. Quit and try restarting AB.
4. AB fails to start and throws a `NullPointerException`

Why
`Commissions` currently store their `Customer`.

`Commissions` are converted from the JSON files into `Commission` objects before their `Customer` objects are created (`java/seedu/address/storage/JsonAdaptedCustomer.java`):
- Lines 91-94: All `Commission`s belonging to the `Customer` are created.
- Line 139: The `Customer` is created
- Line 140: For each `Commission`, `setCustomer` is called to set the association from the Commission to the Customer

You'll notice that lines 91-94 are problematic:
```
 final UniqueCommissionList customerCommissions = new UniqueCommissionList();
        for (JsonAdaptedCommission commission : commissions) {
            customerCommissions.add(commission.toModelType());
        }
```

Because each time `UniqueCommissionList#add` is called, it calls `UniqueCommissionList#contains`, which uses `UniqueCommissionList#isSameCommission` to check for equality between Commissions. Here's `UniqueCommissionList#isSameCommission` for easy reference:
```
    public boolean isSameCommission(Commission otherCommission) {
        if (otherCommission == this) {
            return true;
        }

        return otherCommission != null
                && otherCommission.getTitle().equals(getTitle())
                && otherCommission.getCustomer().equals(getCustomer());
    }
```

Pay particular attention to this line `otherCommission.getCustomer().equals(getCustomer())` and consider the case where you care comparing the 2 duplicate Commissions you just added. You'll see why the `NullPointerException` is being thrown. 😄

**Comment by ngxingyu** [comment]
I agree that this is a major issue, but I believe it can be fixed by #83 since it creates the commission after the customer is created within the `JsonAdaptedCustomer` and ensures that all commissions have a valid non-null customer at all times.
